- name: Wait for Consul API
  ansible.builtin.wait_for:
    host: "{{ consul_bind_addr }}"
    port: 8501
    delay: 5
    timeout: 60

# Check if ACL already bootstrapped by querying leader
- name: Check if ACL bootstrap already done
  ansible.builtin.command: consul acl policy list
  register: acl_check
  failed_when: false
  changed_when: false
  run_once: true
  no_log: true

# Bootstrap only if ACL not initialized
- name: Bootstrap ACL (only if not already bootstrapped)
  ansible.builtin.command: consul acl bootstrap
  register: consul_bootstrap
  run_once: true
  when: "'Permission denied' in acl_check.stderr or acl_check.rc != 0"
  no_log: true
  failed_when: false

# Extract SecretID safely
- name: Extract SecretID
  ansible.builtin.set_fact:
    consul_master_token: "{{ consul_bootstrap.stdout | regex_search('SecretID:\\s+(\\S+)', '\\1') }}"
  when: consul_bootstrap.stdout is defined and consul_bootstrap.stdout != ""
  run_once: true
  no_log: true

# Store token securely on server
- name: Save bootstrap token securely
  ansible.builtin.copy:
    content: "{{ consul_master_token }}"
    dest: /etc/consul.d/bootstrap.token
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
    mode: "0600"
  when: consul_master_token is defined
  run_once: true
  no_log: true

- name: Create agent policy
  ansible.builtin.command: >
    consul acl policy create
    -http-addr=https://127.0.0.1:8501
    -token={{ consul_master_token }}
    -name agent-policy
    -rules 'node_prefix "" { policy = "write" } service_prefix "" { policy = "write" }'
  run_once: true
  ignore_errors: true
  no_log: true


# CREATE AGENT TOKEN
- name: Create agent token
  ansible.builtin.command: >
    consul acl token create
    -http-addr=https://127.0.0.1:8501
    -token={{ consul_master_token }}
    -description "Agent Token"
    -policy-name agent-policy
    -format=json
  register: agent_token_output
  run_once: true
  no_log: true

- name: Extract agent SecretID
  ansible.builtin.set_fact:
    consul_agent_token: "{{ (agent_token_output.stdout | from_json).SecretID }}"
  when: agent_token_output.stdout is defined and agent_token_output.stdout != ""
  run_once: true
  no_log: true

# RESTART CONSUL TO APPLY AGENT TOKEN
- name: Restart consul after token creation
  ansible.builtin.systemd:
    name: consul
    state: restarted
  when: consul_agent_token is defined
