---
- name: Wait for Consul HTTPS API
  ansible.builtin.wait_for:
    host: "{{ consul_bind_addr }}"
    port: 8501
    delay: 5
    timeout: 60

- name: Check if ACL bootstrap already done
  ansible.builtin.command: consul acl policy list
  register: acl_check
  failed_when: false
  changed_when: false
  run_once: true
  no_log: true

- name: Bootstrap ACL (only once)
  ansible.builtin.command: consul acl bootstrap
  register: consul_bootstrap
  run_once: true
  when: acl_check.rc != 0
  no_log: true
  failed_when: false

