---

# - name: Ensure certificate directory is accessible
#   ansible.builtin.file:
#     path: "{{ consul_config_dir }}/certs"
#     state: directory
#     mode: "0755"
#   become: true

# - name: Fix certificate file permissions
#   ansible.builtin.file:
#     path: "{{ consul_config_dir }}/certs/{{ item.file }}"
#     mode: "{{ item.mode }}"
#   loop:
#     - { file: "tls.crt", mode: "0644" }
#     - { file: "tls.key", mode: "0640" }
#   become: true
  
# - name: Copy policy files
#   ansible.builtin.template:
#     src: "policies/{{ item }}.hcl.j2"
#     dest: "/tmp/{{ item }}.hcl"
#     mode: "0644"
#   loop:
#     - agent-policy
#     - service-policy
#     - readonly-policy
#     - monitoring-policy


# - name: List existing policies
#   ansible.builtin.command: consul acl policy list
#   register: existing_policies
#   run_once: true
#   become: true
#   changed_when: false
#   environment: &consul_env
#     CONSUL_HTTP_ADDR: "https://{{ consul_bind_addr }}:8501"
#     CONSUL_HTTP_TOKEN: "{{ consul_master_token }}"
#     CONSUL_CACERT: "{{ consul_config_dir }}/certs/tls.crt"  
#     CONSUL_HTTP_SSL_VERIFY: "false"

# - name: Create Consul policies
#   ansible.builtin.command: >
#     consul acl policy create
#     -name {{ item }}
#     -rules @/tmp/{{ item }}.hcl
#   loop:
#     - agent-policy
#     - service-policy
#     - readonly-policy
#     - monitoring-policy
#   when: item not in existing_policies.stdout
#   run_once: true
#   environment: *consul_env



- name: List existing policies
  ansible.builtin.command: consul acl policy list
  register: existing_policies
  run_once: true
  become: true
  changed_when: false
  environment: &consul_env
    # CHANGE 1: Use https instead of http
    CONSUL_HTTP_ADDR: "https://{{ consul_bind_addr }}:8501"
    CONSUL_HTTP_TOKEN: "{{ consul_master_token }}"
    
    # CHANGE 2: Uncomment and provide the cert files for the handshake
    CONSUL_CACERT: "{{ consul_config_dir }}/certs/tls.crt"
    CONSUL_CLIENT_CERT: "{{ consul_config_dir }}/certs/tls.crt"
    CONSUL_CLIENT_KEY: "{{ consul_config_dir }}/certs/tls.key"
    
    # CHANGE 3: Add the Server Name to match your cert (opstree.dev)
    CONSUL_TLS_SERVER_NAME: "opstree.dev"
    CONSUL_HTTP_SSL_VERIFY: "false"




