---
- name: Copy policy files
  ansible.builtin.template:
    src: "policies/{{ item }}.hcl.j2"
    dest: "/tmp/{{ item }}.hcl"
    mode: "0644"
  loop:
    - agent-policy
    - service-policy
    - readonly-policy

- name: List existing policies
  ansible.builtin.command: consul acl policy list
  register: existing_policies
  run_once: true
  become: true
  changed_when: false
  environment: &consul_env
    CONSUL_HTTP_ADDR: "https://{{ consul_bind_addr }}:8501"
    CONSUL_HTTP_TOKEN: "{{ consul_master_token }}"
    CONSUL_CACERT: "{{ consul_config_dir }}/certs/tls.crt"
    CONSUL_CLIENT_CERT: "{{ consul_config_dir }}/certs/tls.crt"  
    CONSUL_CLIENT_KEY: "{{ consul_config_dir }}/certs/tls.key"    
    CONSUL_HTTP_SSL_VERIFY: "false"

- name: Create Consul policies
  ansible.builtin.command: >
    consul acl policy create
    -name {{ item }}
    -rules @/tmp/{{ item }}.hcl
  loop:
    - agent-policy
    - service-policy
    - readonly-policy
  when: item not in existing_policies.stdout
  run_once: true
  environment: *consul_env
