---
- name: Create TLS cert directory
  ansible.builtin.file:
    path: "{{ consul_config_dir }}/certs"
    state: directory
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
    mode: "0750"

- name: Copy CA certificate
  ansible.builtin.copy:
    src: consul-agent-ca.pem
    dest: "{{ consul_config_dir }}/certs/consul-agent-ca.pem"
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
    mode: "0644"

- name: Copy Server certificate
  ansible.builtin.copy:
    src: dc1-server-consul-0.pem
    dest: "{{ consul_config_dir }}/certs/dc1-server-consul-0.pem"
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
    mode: "0644"

- name: Copy Server key
  ansible.builtin.copy:
    src: dc1-server-consul-0-key.pem
    dest: "{{ consul_config_dir }}/certs/dc1-server-consul-0-key.pem"
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
    mode: "0600"

- name: Deploy Consul server configuration
  ansible.builtin.template:
    src: server.hcl.j2
    dest: "{{ consul_config_dir }}/server.hcl"
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
    mode: "0640"
  notify: Restart Consul
