# - name: Create TLS cert directory
#   ansible.builtin.file:
#     path: "{{ consul_config_dir }}/certs"
#     state: directory
#     owner: "{{ consul_user }}"
#     group: "{{ consul_group }}"
#     mode: "0750"

# - name: Copy TLS certificate
#   ansible.builtin.copy:
#     src: tls.crt
#     dest: "{{ consul_config_dir }}/certs/tls.crt"
#     owner: "{{ consul_user }}"
#     group: "{{ consul_group }}"
#     mode: "0644"
#   notify: Restart Consul

# - name: Copy TLS private key
#   ansible.builtin.copy:
#     src: tls.key
#     dest: "{{ consul_config_dir }}/certs/tls.key"
#     owner: "{{ consul_user }}"
#     group: "{{ consul_group }}"
#     mode: "0600"
#   notify: Restart Consul

- name: Deploy Consul server configuration
  ansible.builtin.template:
    src: server.hcl.j2
    dest: "{{ consul_config_dir }}/server.hcl"
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
    mode: "0640"
  notify: Restart Consul


# - name: Read service token from server
#   ansible.builtin.slurp:
#     src: "{{ consul_config_dir }}/service.token"
#   register: remote_service_token

# - name: Register Keycloak POC Service
#   ansible.builtin.template:
#     src: keycloak-service.json.j2
#     dest: "{{ consul_config_dir }}/keycloak.json"
#     owner: "{{ consul_user }}"
#     group: "{{ consul_group }}"
#     mode: "0640"
#   vars:
#     # This decodes the base64 token from the remote server
#     actual_service_token: "{{ remote_service_token['content'] | b64decode | trim }}"
#   notify: Restart Consul
