- name: Installing Unzip
  apt:
    name: unzip
    state: present

- name: Downloading consul binary
  get_url:
    url: https://releases.hashicorp.com/consul/1.7.2/consul_1.7.2_linux_amd64.zip
    dest: /usr/local/bin/
    mode: '0440'
  register: consul_download_result

- name: Extracting and then removing the zip file
  shell: |
    cd /usr/local/bin/
    rm -rf consul
    unzip *.zip
    rm *.zip
    chown root:root consul
  when: consul_download_result is succeeded

- name: Adding a non-privileged user 'consul' with no shell
  user:
    name: consul
    home: /etc/consul.d
    shell: /bin/false


- name: Creating directories for consul persistent storage
  file:
    path: /opt/consul/
    state: directory
    owner: consul
    group: consul

- name: Creating a Consul service file
  copy:
    dest: "/etc/systemd/system/consul.service"
    content: |
        [Unit]
        Description="HashiCorp Consul - A service mesh solution"
        Documentation=https://www.consul.io/
        Requires=network-online.target
        After=network-online.target
        ConditionFileNotEmpty=/etc/consul.d/consul.hcl
        
        [Service]
        Type=notify
        User=consul
        Group=consul
        ExecStart=/usr/local/bin/consul agent -config-dir=/etc/consul.d/
        ExecReload=/usr/local/bin/consul reload
        KillMode=process
        Restart=on-failure
        LimitNOFILE=65536
        
        [Install]
        WantedBy=multi-user.target

- name: Creating consul.hcl file for server1
  when: "ansible_default_ipv4.address == ip_list.split(',')[0]"
  copy:
    dest: "/etc/consul.d/consul.hcl"
    owner: consul
    group: consul
    mode: '0640'
    content: |
        datacenter = "dc1"
        data_dir = "/opt/consul"
        encrypt = "sH0yrNhlGMoonafcfmNPr6kkHq/rXb0XhUbE4IUrfvA="
        retry_join = ["{{ ip_list.split(",")[1] }}", "{{ ip_list.split(",")[2] }}"]
        performance {
            raft_multiplier = 1
        }

- name: Creating consul.hcl file for server2
  when: "ansible_default_ipv4.address == ip_list.split(',')[1]"
  copy:
    dest: "/etc/consul.d/consul.hcl"
    owner: consul
    group: consul
    mode: '0640'
    content: |
        datacenter = "dc1"
        data_dir = "/opt/consul"
        encrypt = "sH0yrNhlGMoonafcfmNPr6kkHq/rXb0XhUbE4IUrfvA="
        retry_join = ["{{ ip_list.split(",")[0] }}", "{{ ip_list.split(",")[2] }}"]
        performance {
            raft_multiplier = 1
        }

- name: Creating consul.hcl file for server3
  when: "ansible_default_ipv4.address == ip_list.split(',')[2]"
  copy:
    dest: "/etc/consul.d/consul.hcl"
    owner: consul
    group: consul
    mode: '0640'
    content: |
        datacenter = "dc1"
        data_dir = "/opt/consul"
        encrypt = "sH0yrNhlGMoonafcfmNPr6kkHq/rXb0XhUbE4IUrfvA="
        retry_join = ["{{ ip_list.split(",")[0] }}", "{{ ip_list.split(",")[1] }}"]
        performance {
            raft_multiplier = 1
        }

- name: Creating server.hcl file
  copy:
    dest: "/etc/consul.d/server.hcl"
    owner: consul
    group: consul
    mode: '0640'
    content: |
        server = true
        bootstrap_expect = 3

- name: Enabling and starting consul
  shell: |
    set timeout 600
    systemctl enable consul
    systemctl restart consul
