---
- hosts: all
  vars:
    priv_ip: "{{ ansible_default_ipv4.address }}"
    server_name: "{{ inventory_hostname }}"
  become: yes
  become_user: root
  gather_facts: yes
  tasks:
    - name: Create List of nodes ip's
      set_fact: 
        ip_list: "{{ groups['consul-servers'] | map('extract', hostvars, ['ansible_eth0', 'ipv4', 'address']) | join(',') }}"

    - import_role:
        name: common

    - import_role:
        name: consulServer

