---
- hosts: all
  vars:
    priv_ip: [10.0.0.4, 10.0.0.7, 10.0.0.8]
  become: yes
  become_user: root
  gather_facts: yes
  tasks:
    - import_role:
        name: common

    - import_role:
        name: consulServer