- name: Installing python-pip
  apt:
    name: python-pip
    state: present

- name: Installing python-consul with pip
  pip:
    name: python-consul
    state: present

- name: Register nginx with an http check
  consul:
    service_name: "{{ service_name }}"
    service_port: "{{ service_port }}"
    interval: "{{ health_check_interval }}"
    http: "{{ health_check_url }}"
