- name: Creating consul user 
  user:
    name: "{{ consul_user }}"
    state: present
    shell: "{{ consul_user_shell }}"
    createhome: no

# Creating configuration , data and log directory and assigning consul owner & group on it 
- name: Creating configuration, data and log directory if it does not exist
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
    mode: "{{ consul_dir_mode }}"
  with_items:
  - "{{ consul_configd_path }}"
  - "{{ consul_data_path }}"
  - "{{ consul_logdir }}"