- name: Update apt
  apt:
    update_cache: yes

- name: Installing unzip 
  apt: 
    name: "{{ addon_package }}"
    state: present 

- name: Download consul 
  unarchive: 
    src: "{{ consul_url }}"
    dest: "{{ consul_bin_path }}"
    owner: "{{ consul_binary_owner }}"
    group: "{{ consul_binary_group }}"
    remote_src: yes

- name: Creating consul user and directories
  include: consul_user.yml

- name: check consul_keygenerate file
  stat:
    path: "{{ consul_keygenerate_file }}"
  register: info
  
- name: check if key is already generated 
  debug:
    msg: Key already generated
  when: info.stat.exists

- name: "If key not generated then generate it"
  shell: "consul keygen > {{ consul_keygenerate_file }}"
  when: not info.stat.exists

- name: save remote file content
  slurp:
    src: "{{ consul_keygenerate_file }}"
  register: encrypt_key
  
- name: Send consul configuration file
  template:
    src: "{{ item.src_file }}"
    dest: "{{ item.dest_file }}"
    mode: "{{ consul_service_mode }}"
  notify:
    - daemon_reload 
    - restart_consul
  loop:
    - { src_file: "{{ consul_config_src }}", dest_file: "{{ consul_config_dest }}" }
    - { src_file: "{{ consul_service_src }}", dest_file: "{{ consul_service_dest }}" }