- name: Creating consul user 
  user:
    name: "{{ consul_user }}"
    state: present
    shell: "{{ consul_user_shell }}"
    createhome: no
  
- name: Create a consul and consul.d directory if it does not exist
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
    mode: "{{ consul_dir_mode }}"
  with_items:
  - "{{ consul_configd_path }}"
  - "{{ consul_data_path }}"