- name: Downloading consul binary
  get_url:
    url: "{{ consul_binary_url }}"
    dest: "{{ consul_binary_dir }}"
    mode: "{{ consul_binary_perm }}"
  register: consul_download_result

- name: Extracting and then removing the zip file
  shell: |
    cd "{{ consul_binary_dir }}"
    rm -rf consul
    unzip *.zip
    rm *.zip
    chown "{{ consul_binary_owner }}":"{{ consul_binary_group }}" consul
  when: consul_download_result is succeeded