- name: Removing previous consul binary if exist
  file:
    path: "{{ consul_binary_dir }}/consul"
    state: absent

- name: Downloading archived consul binary
  unarchive:
    src: "{{ consul_binary_url }}"
    dest: "{{ consul_binary_dir }}"
    owner: "{{ consul_binary_owner }}"
    group: "{{ consul_binary_group }}"
    remote_src: yes
