---
-   name: Including file for consul binary
    include: consul-binary.yml
    tags:
        - consul-cluster
        - consul-server
        - consul-client     

-   name: Executing command to generate encrypt key
    when: "ansible_default_ipv4.address == ip_list.split(',')[0]"
    command: consul keygen
    run_once: true
    register: key_encrypt
    tags:
        - consul-cluster

-   name: Including file for consul user
    include: consul-user.yml
    tags:
        - consul-cluster
        - consul-server
        - consul-client      

- name: Creating a Consul service file
  template:
    src: consul-service.j2
    dest: "{{ consul_service_file }}"
    tags:
        - consul-cluster
        - consul-server
        - consul-client    

-   name: Including file for consul hcl for cluster
    include: consul-hcl-3node-cluster.yml
    tags:
        - consul-cluster    

- name: Creating consul.hcl file
  template:
    src: consul-hcl.j2
    dest: "{{ consul_hcl_dest }}"
    tags:
        - consul-server
        - consul-client

-   name: Creating server.hcl file
    template:
        src: server-hcl-cluster.j2
        dest: "{{ server_hcl_dest }}"
        owner: "{{ consul_owner }}"
        group: "{{ consul_group }}"
        mode: "{{ server_hcl_mode }}"
    tags:
        - consul-cluster   

-   name: Creating server.hcl file
    template:
        src: server-hcl.j2
        dest: "{{ server_hcl_dest }}"
        owner: "{{ consul_owner }}"
        group: "{{ consul_group }}"
        mode: "{{ server_hcl_mode }}"
    tags:
        - consul-server   

-   name: Including file for registering and modifying services in consul-agent
    include: amd.yml
    tags:
        - consul-amd

-   name: Reloading systemd and restarting consul
    command: /bin/true
    notify: 
        - daemon_reload
        - restart_consul
    tags:
        - consul-cluster
        - consul-server
        - consul-client
        - consul-amd
