---
- name: Create Keycloak JWT Auth Method
  ansible.builtin.command: >
    consul acl auth-method create
    -name "keycloak"
    -type "jwt"
    -description "JWT Authentication via Keycloak"
    -config '{
      "JWKSURL": "{{ keycloak_url }}/realms/{{ keycloak_realm }}/protocol/openid-connect/certs",
      "JWTSupportedAlgs": ["RS256"],
      "BoundIssuer": "{{ keycloak_url }}/realms/{{ keycloak_realm }}"
    }'
  environment:
    CONSUL_HTTP_ADDR: "https://127.0.0.1:{{ consul_https_port }}"
    CONSUL_HTTP_TOKEN: "{{ consul_master_token }}"
    CONSUL_HTTP_SSL_VERIFY: "false"
  run_once: true
  register: jwt_method_out
  failed_when: 
    - jwt_method_out.rc != 0 
    - "'already exists' not in jwt_method_out.stderr"

- name: Create Binding Rule for JWT Users
  ansible.builtin.command: >
    consul acl binding-rule create
    -method "keycloak"
    -bind-type "policy"
    -bind-name "readonly-policy"
    -selector "true"
  environment:
    CONSUL_HTTP_ADDR: "https://127.0.0.1:{{ consul_https_port }}"
    CONSUL_HTTP_TOKEN: "{{ consul_master_token }}"
    CONSUL_HTTP_SSL_VERIFY: "false"
  run_once: true
  register: binding_rule_out
  failed_when:
    - binding_rule_out.rc != 0
    - "'already exists' not in binding_rule_out.stderr"
