---

- name: Check Consul leader
  command: consul operator raft list-peers
  register: consul_peers
  changed_when: false


- name: Show Consul peers
  debug:
    var: consul_peers.stdout


- name: Check Consul DNS port
  wait_for:
    port: 8600
    timeout: 10
