---
# defaults file for consul
consul_version: "1.17.0"
consul_user: "consul"
consul_group: "consul"

consul_install_dir: "/usr/local/bin"
consul_data_dir: "/var/lib/consul"
consul_config_dir: "/etc/consul.d"

consul_node_name: "{{ inventory_hostname }}"
consul_bind_addr: "{{ ansible_default_ipv4.address }}"

consul_is_server: true
consul_bootstrap_expect: "{{ groups['consul_servers'] | length }}"

consul_enable_ui: true

# ACL
consul_acl_enabled: true
consul_acl_default_policy: "deny"
consul_acl_token_persistence: true
consul_agent_token: ""
